---
# 1. Configure optional tools on controller node

# Install `docker.io` with apt.
use_docker_io: false

# Use the latest vim on `ppa:jonathonf/vim`, and use plugins with
# vim-plug.
use_vim_latest: true
use_vim_extra_plugins: true

# Clone tacker in addition to devstack.
use_tacker: true

# Use tools useful for developing.
use_extra_tools: true

# 2. Devstack params
# common
admin_password: devstack
database_password: devstack
rabbit_password: devstack
service_password: devstack

# compute nodes
service_host: 192.168.33.11
floating_range: 192.168.33.128/25
fixed_range: 10.4.128.0/20
