---

# Configure optional tools on controller node 

# Install `docker.io` with apt.
use_docker_io: false

# Use the latest vim on `ppa:jonathonf/vim`, and use plugins with
# vim-plug.
use_vim_latest: true
use_vim_extra_plugins: true

# Clone tacker in addition to devstack.
use_tacker: true

# Use tools useful for developing.
use_extra_tools: true
