---
- name: ubuntu-focal  controller node
  hosts: ubuntu-focal.controller
  remote_user: stack
  roles:
      - ubuntu-focal/controller

- name: ubuntu-focal compute nodes
  hosts: ubuntu-focal.compute
  remote_user: stack
  roles:
      - ubuntu-focal/compute

- name: centos8 controller node
  hosts: centos-8.controller
  remote_user: stack
  roles:
      - centos-8/controller
