---
- name: controller node
  hosts: ubuntu-focal.controller
  remote_user: stack
  roles:
      - ubuntu-focal/controller

- name: compute nodes
  hosts: ubuntu-focal.compute
  remote_user: stack
  roles:
      - ubuntu-focal/compute
